version: "3.9"

services:
  db:
    image: postgres:17-alpine3.21
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5439:5432"
      
networks:
  default:
    driver: bridge
